name: fno_class
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12.3
  - pytorch=2.7.1
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - h5py
  - tqdm
  - pip